site_name: FileThis Developer Docs

pages:
    - 'Home': 'index.md'
    - Webcomponent Integrations:
        - 'Demo App': 'ft-connect-demo.md'
        - 'Minimal Site App': 'ft-connect-minimal-site.md'
#    - API Integrations:
#        - 'First': 'ft-api-first.md'
#        - 'Second': 'ft-api-second.md'
