site_name: FileThis Developer Docs

theme: readthedocs

site_favicon: favicon.ico

pages:
- Home: index.md
- Front End SDK:
    - The Development Tool: front-end/ft-connect-demo.md
    - Exploring a Rendered Component: front-end/ft-rendered-component.md
    - Code Generation: front-end/ft-code-generation.md
    - Embedding into a Minimal Site: front-end/ft-connect-minimal-site.md
#- Back End SDK:
#    - Overview: back-end/placeholder.md
#- Administration:
#    -Overview: admin/placeholder.md
