site_name: FileThis Developer Docs

pages:
    - 'Home': 'index.md'
    - FileThisConnect Webcomponent:
        - 'FileThisConnect Demo': 'ft-connect-demo.md'
        - 'FileThisConnect Minimal Site': 'ft-connect-minimal-site.md'
    - FileThis API Integration:
        - 'First': 'ft-api-first.md'
        - 'Second': 'ft-api-second.md'
